### PR TITLE
Add a document explaining how we route requests from an HTTP request to app containers

### PR DESCRIPTION
**Pull request by alexwlchan**
Rendered version: https://github.com/wellcomecollection/storage-service/blob/request-routing/docs/how-are-requests-routed.md

Part of https://github.com/wellcomecollection/platform/issues/5206

It's possible to work this out by staring at the Terraform, but API Gateway in particular makes this quite non-obvious, and having it written out in a one-pager feels like something useful to have.

### CODE REVIEW

**Comment by kenoir** [comment]
Nice. It might help to include some references to how ports are used at each step, as that will be relevant for reconciling the doc with the code. For example at nginx / vpc link stages we are routing from one port to another - you might want to highlight that.

**Comment by alexwlchan** [comment]
> It might help to include some references to how ports are used at each step, as that will be relevant for reconciling the doc with the code. For example at nginx / vpc link stages we are routing from one port to another - you might want to highlight that.

Good suggestion, done.

**Comment by alexwlchan** [comment]
I forgot to mention Route 53/DNS entries. >.<

**Comment by alexwlchan** [comment]
Superseded by another PR.

**Pull request closed without merging**
